on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Try CalVer to SemVer Release
    steps:
      - uses: actions/checkout@v2
      - id: calver-to-semver-release
        uses: AryeoHQ/gh-action-calver-to-semver-release@1.0.0
        with:
          calver: 2020-07-02
          calver-count: 2
          latest-semver: 1.0.3
      - run: |
          echo semver ${{ steps.calver-to-semver-release.outputs.semver }}
          echo notes ${{ steps.calver-to-semver-release.outputs.notes }}
        shell: bash
